### ISSUE TITLE
Wrong bit offset for word length selection

### ISSUE THREAD

**Issue by dublevskyi** [umanovskis/baremetal-arm#2]
According to the [PrimeCell UART (PL011) TRM](http://infocenter.arm.com/help/topic/com.arm.doc.ddi0183f/DDI0183.pdf) word length bits are [6:5], so I'm pretty sure the offset should be 5 instead of 6

https://github.com/umanovskis/baremetal-arm/blob/dcee0f86222f58735acd478226b96d3c232fc7a4/src/06_uart/src/uart_pl011.h#L52-L55

**Comment by umanovskis** [comment]
You're right of course. Will fix shortly.

**Comment by dumanovskis** [comment]
Commit 4ce7973889 fixes the offset.

**Comment by umanovskis** [comment]
Commit 4ce7973889b fixes the offset.
